version: '3.8'

services:
  # The FastAPI web server
  web:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 15s
      timeout: 5s
      retries: 5

  # The autonomous trading agent
  agent:
    build: .
    env_file:
      - .env
    command: python -m src.agent --ticker NVDA
    volumes:
      - ./:/app
    depends_on:
      web:
        condition: service_healthy